### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by israelshirk** [mekwall/koa-ws#12]
Hey, I just wanted to check and see if you're still keeping this project alive and, if so, would be able to make a release with the last merge?  And if not, would you be open to adding me as a collaborator?  Thanks!  Israel

**Comment by mekwall** [comment]
Sadly no. I haven't had the use, time or energy to continue development. You're welcome to take over ownership if you'd like.

**Comment by israelshirk** [comment]
Got it, thanks!  Could you run `npm owner add israelshirk` to get me on NPM as well?

**Comment by mekwall** [comment]
Done! 👍
